/*
 * SPDX-FileCopyrightText: 2026 KDE Contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef M3COLORENGINE_H
#define M3COLORENGINE_H

#include "dolphin_export.h"

#include <QColor>
#include <QFileSystemWatcher>
#include <QObject>
#include <QPalette>
#include <QString>

struct DOLPHIN_EXPORT M3ColorScheme {
    bool isDark = true;

    // Tonal Surfaces
    QColor surface;
    QColor onSurface;
    QColor surfaceVariant;
    QColor onSurfaceVariant;
    QColor surfaceContainerLowest;
    QColor surfaceContainerLow;
    QColor surfaceContainer;
    QColor surfaceContainerHigh;
    QColor surfaceContainerHighest;
    QColor surfaceDim;
    QColor surfaceBright;
    QColor surfaceTint;
    QColor inverseSurface;
    QColor inverseOnSurface;

    // Accent Tokens
    QColor primary;
    QColor onPrimary;
    QColor primaryContainer;
    QColor onPrimaryContainer;
    QColor inversePrimary;

    QColor secondary;
    QColor onSecondary;
    QColor secondaryContainer;
    QColor onSecondaryContainer;

    QColor tertiary;
    QColor onTertiary;
    QColor tertiaryContainer;
    QColor onTertiaryContainer;

    QColor error;
    QColor onError;
    QColor errorContainer;
    QColor onErrorContainer;

    // Outlines & Elevation
    QColor outline;
    QColor outlineVariant;
    QColor shadow;
    QColor scrim;

    // Helpers
    static M3ColorScheme defaultDark();
    static M3ColorScheme defaultLight();
    QColor stateLayer(const QColor &base, const QColor &content, qreal alpha) const;
};

/**
 * @brief Singleton color token ingestion and live-mutation engine for Material Design 3.
 *
 * Ingests dynamic JSON generated by Matugen at ~/.cache/matugen/colors.json and provides
 * hot-reloading signals and palette mutation across Dolphin widgets.
 */
class DOLPHIN_EXPORT M3ColorEngine : public QObject
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.dolphin.M3ColorEngine")

public:
    static M3ColorEngine *instance();

    const M3ColorScheme &scheme() const;
    bool isDark() const;

    QPalette generateQPalette() const;
    QPalette generateQPalette(const M3ColorScheme &scheme) const;

    QString colorsFilePath() const;
    void setCustomColorsFilePath(const QString &path);

    qint64 lastIngestionDurationUs() const;

public Q_SLOTS:
    /**
     * @brief Slot callable via D-Bus or timer to reload Matugen color tokens instantly.
     */
    Q_SCRIPTABLE void reloadColors();

Q_SIGNALS:
    void colorsChanged(const M3ColorScheme &scheme);

private Q_SLOTS:
    void onFileChanged(const QString &path);
    void onDirectoryChanged(const QString &path);

private:
    explicit M3ColorEngine(QObject *parent = nullptr);
    ~M3ColorEngine() override;

    void setupWatcher();
    bool parseJsonFile(const QString &filePath, M3ColorScheme &targetScheme);
    void applyPaletteToApplication();

    M3ColorScheme m_scheme;
    QFileSystemWatcher m_fileWatcher;
    QString m_colorsFilePath;
    qint64 m_lastIngestionDurationUs = 0;
};

#endif // M3COLORENGINE_H
